### ISSUE TITLE
projectBundleFromTestrunClosure copies everything from referenced derivations

### ISSUE THREAD

**Issue by parthy** [cyberus-technology/cbspkgs-public#33]
When referencing a certain file in a project config that comes from a derivation with additional files that are not referenced in the config, the helper will still copy the entirety into the resulting ZIP archive. A prominent example is a Linux kernel that comes with the `bzImage`, but also potentially a large number of compiled modules, which then all get copied into the archive. The difference here is roughly 5 MiB <-> 90 MiB. Depending on the nature of the derivation, this could get much worse and wastes a lot of space. Since the list of referenced files is 100% clear from the project config, it seems unnecessary to include anything else in the archive.

**Comment by parthy** [comment]
This might also have some overlap with #26 when it comes to which paths to include.

**Comment by kaldonir** [comment]
This functionality has been removed, and replaced by `mkProjectBundle` from #34.
